// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptzEgtyVa-35BHSRWEAjZk3VlhA9jO4A',
    appId: '1:400226249296:web:61a324c4170183c8833f55',
    messagingSenderId: '400226249296',
    projectId: 'papa-entulho-26c99',
    authDomain: 'papa-entulho-26c99.firebaseapp.com',
    storageBucket: 'papa-entulho-26c99.firebasestorage.app',
    measurementId: 'G-4C0Z7SP18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTSJezx7UXGDn5d8jmhdVZQWbu2Hbu7-I',
    appId: '1:400226249296:android:d14e10204f0ed01e833f55',
    messagingSenderId: '400226249296',
    projectId: 'papa-entulho-26c99',
    storageBucket: 'papa-entulho-26c99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiN5KMdtTQ9YS-wHu_8Opked5mcadXNck',
    appId: '1:400226249296:ios:a9ffee68a48a2f2c833f55',
    messagingSenderId: '400226249296',
    projectId: 'papa-entulho-26c99',
    storageBucket: 'papa-entulho-26c99.firebasestorage.app',
    iosBundleId: 'com.nicholasvp.papaEntulho',
  );
}
